# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-File
version:      0.10
version_from: lib/Audio/File.pm
installdirs:  site
requires:
    Audio::FLAC::Header:           0
    MP3::Info:                     0
    MP3::Tag:                      0
    Ogg::Vorbis::Header::PurePerl: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
